version: '2.3'
services:
  http_server:
    build:
      context: ./HTTP_Server
      dockerfile: Dockerfile
    image: bgoldstone/http_server
    container_name: ztp_http_server
    # This container is only really useful in host networking mode
    network_mode: "host"
    # TODO: Find minimum privileges
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./HTTP_Server/served_assets:/usr/local/run
    command: ["bash", "/usr/local/run/run_http_server.sh"]
